# ansible/setup.yml

- name: Install node and npm
  ansible.builtin.apt:
    name:
      - nodejs
      - npm
    state: latest
    update_cache: yes

- name: Remove existing nodeapp directory for clean deployment
  ansible.builtin.file:
    path: /home/ubuntu/nodeapp/
    state: absent

- name: Copy Node.js app files from GitHub Actions workspace to EC2
  ansible.builtin.synchronize:
    src: "{{ playbook_dir }}/roles/nodejs/files/codebase/"
    dest: /home/ubuntu/nodeapp/
    mode: push 
    recursive: yes 
    perms: yes 
    owner: yes 
    group: yes 
  notify:
    - Reload nodeapp

- name: Ensure correct ownership for Node.js app directory
  ansible.builtin.file:
    path: /home/ubuntu/nodeapp/
    owner: ubuntu
    group: ubuntu
    mode: '0755' # Asegura permisos de ejecución para el directorio
    recurse: yes # Aplica los cambios recursivamente a todo el contenido
    state: directory # Asegura que el path es un directorio


- name: Copy nodeapp.service file
  ansible.builtin.copy:
    src: ../files/service/nodeapp.service
    dest: /etc/systemd/system/nodeapp.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd
    - Enable and start nodeapp
