# roles/nginx/tasks/main.yml
---
- name: Install nginx
  ansible.builtin.apt: 
    name: nginx
    state: latest
    update_cache: yes

- name: Remove default nginx configuration
  ansible.builtin.file: 
    path: /etc/nginx/nginx.conf
    state: absent

- name: Remove default nginx configuration
  ansible.builtin.file: 
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Add nginx configuration
  ansible.builtin.copy: 
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: www-data
    group: www-data
    mode: '0644'
  notify: Reload Nginx 

- name: Ensure nginx is running
  ansible.builtin.systemd: 
    name: nginx
    state: started
    enabled: yes
